=== AlejandroAlcaraz32/MotorIndationIber/maven/src/main/resources/jsonSchemaFiles/schema-dataset.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1646063812.json",
  "title": "Root",
  "type": "object",
  "required": [
    "name",
    "description",
    "sourceName",
    "typ",
    "version",
    "enabled",
    "ingestionMode",
    "validationMode",
    "createDatabase",
    "classification",
    "database",
    "table",
    "partitionBy",
    "permissiveThresholdType",
    "permissiveThreshold",
    "schemaDefinition"

  ],
  "properties": {
    "datasetId": {
      "$id": "#root/datasetId",
      "title": "Datasetid",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "sourceId": {
      "$id": "#root/sourceId",
      "title": "sourceId",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "specificationId": {
      "$id": "#root/specificationId",
      "title": "specificationId",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "name": {
      "$id": "#root/name",
      "title": "Name",
      "type": "string",
      "default": "",
      "examples": [
        "dataset1"
      ],
      "pattern": "^.*$"
    },
    "description": {
      "$id": "#root/description",
      "title": "Description",
      "type": "string",
      "default": "",
      "examples": [
        "Dataset 1"
      ],
      "pattern": "^.*$"
    },
    "sourceName": {
      "$id": "#root/sourceName",
      "title": "Sourcename",
      "type": "string",
      "default": "",
      "examples": [
        "source1"
      ],
      "pattern": "^.*$"
    },
    "typ": {
      "$id": "#root/typ",
      "title": "Typ",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "fileInput": {
      "$id": "#root/fileInput",
      "title": "Fileinput",
      "type": "object",
      "required": [
        "format",
        "filePattern"
      ]
    },
    "kafkaInput": {
      "$id": "#root/kafkaInput",
      "title": "Kafkainput",
      "type": "object",
      "required": [
        "topicKey",
        "groupId",
        "jaasConfigurationKey"
      ]
    },
    "tableInput": {
      "$id": "#root/tableInput",
      "title": "Tableinput",
      "type": "object",
      "required": [
        "table"
      ]
    },
    "apiInput": {
      "$id": "#root/apiInput",
      "title": "APIinput",
      "type": "object",
      "required": [
        "endpoint",
        "pagination"
      ]
    },
    "version": {
      "$id": "#root/version",
      "title": "Version",
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "enabled": {
      "$id": "#root/enabled",
      "title": "Enabled",
      "type": "boolean",
      "examples": [
        true
      ],
      "default": true
    },
    "effectiveDate": {
      "$id": "#root/effectiveDate",
      "title": "Effectivedate",
      "type": "string",
      "default": "",
      "examples": [
        "2020-07-03 10:10:00"
      ],
      "pattern": "^.*$"
    },
    "ingestionMode": {
      "$id": "#root/ingestionMode",
      "title": "Ingestionmode",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "validationMode": {
      "$id": "#root/validationMode",
      "title": "Validationmode",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "createDatabase": {
      "$id": "#root/createDatabase",
      "title": "Createdatabase",
      "type": "boolean",
      "examples": [
        false
      ],
      "default": true
    },
    "classification": {
      "$id": "#root/classification",
      "title": "Classification",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "database": {
      "$id": "#root/database",
      "title": "Database",
      "type": "string",
      "default": "",
      "examples": [
        "database1"
      ],
      "pattern": "^.*$"
    },
    "table": {
      "$id": "#root/table",
      "title": "Table",
      "type": "string",
      "default": "",
      "examples": [
        "table1"
      ],
      "pattern": "^.*$"
    },
    "partitionBy": {
      "$id": "#root/partitionBy",
      "title": "Partitionby",
      "type": "string",
      "default": "",
      "examples": [
        "yyyy/mm/dd"
      ],
      "pattern": "^.*$"
    },
    "allowPartitionChange": {
      "$id": "#root/allowPartitionChange",
      "title": "Allowpartitionchange",
      "type": "boolean",
      "examples": [
        false
      ],
      "default": true
    },
    "permissiveThresholdType": {
      "$id": "#root/permissiveThresholdType",
      "title": "Permissivethresholdtype",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "permissiveThreshold": {
      "$id": "#root/permissiveThreshold",
      "title": "Permissivethreshold",
      "type": "integer",
      "examples": [
        10
      ],
      "default": 0
    },
    "schemaDefinition": {
      "$id": "#root/schemaDefinition",
      "title": "Schemadefinition",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "schemaFile": {
      "$id": "#root/schemaFile",
      "title": "Schemafile",
      "type": "string",
      "default": "",
      "examples": [
        "/source1/dataset1/avro-schema.json"
      ],
      "pattern": "^.*$"
    },
    "schemaColumns": {
      "$id": "#root/schemaColumns",
      "title": "Schemacolumns",
      "type": "object",
      "required": [
        "columns"
      ]
    },
    "schemaJson": {
      "$id": "#root/schemaJson",
      "title": "Schemajson",
      "type": "object",
      "required": [
        "type",
        "fields"
      ]
    },
    "qualityRules": {
      "$id": "#root/qualityRules",
      "title": "Qualityrules",
      "type": "object",
      "required": [
        "mode"
      ]
    }
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-sqlserver/dataset-sqlserver/dataset-sqlserver-fullsnapshotExtraColumns.json
{
  "name": "dataset-sqlserver-fullsnapshot-extra-columns-ok",
  "description": "dataset sqlserver full snapshot with more columns in table than json",
  "sourceName": "source-sqlserver",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "Production",
  "table": "ProductCategoryFSEC",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "tableInput":{
    "table": "ProductCategory",
    "schema": "Production"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "ProductCategoryID",
        "typ": {"value":  "integer"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-excel-6/dataset-full-snapshot-datarange-worldcities/dataset-full-snapshot-datarange-worldcities.json
{
  "name": "full-snapshot-datarange-worldcities",
  "description": "Dataset Full Snapshot World Cities",
  "sourceName": "source-excel-6",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database6",
  "table": "full_snapshot_datarange_worldcities",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "xls" },
    "filePattern": "<yyyy><mm><dd>_datarange_worldCities.xls",
    "xls": {
      "header": { "value": "first_line"},
      "dataRange": "A1"
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "country",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "geonameid",
        "typ": {"value":  "long"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      },
      {
        "name": "timeStamp",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 5,
        "sensitive": false,
        "transformation" : {
          "typ": {"value": "date"},
          "pattern": "yyyy-MM-dd HH:mm:ss"
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-api/dataset-api-sensitive/dataset-api-sensitive.json
{
  "name": "dataset-api-sensitive",
  "description": "dataset api sensitive",
  "sourceName": "source-api",
  "typ": { "value": "api" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database_api",
  "table": "api_sensitive",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "apiInput":{
    "endpoint": "People",
    "parameters": "",
    "pagination": {
      "typ": {"value" :"offset"},
      "top": "$top",
      "skip": "$skip",
      "topSize": 10
    },
    "dataIn": "value",
    "headers": {
      "content-type": "json"
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "/source-api/dataset-api-full/dataset-api-fullsnapshot_schema.json",
  "schemaColumns": {
    "columns": [
      {
        "name": "UserName",
        "typ": {"value":  "string"},
        "isPrimaryKey": true,
        "position": 1,
        "sensitive": true
      },
      {
        "name": "Concurrency",
        "typ": {"value":  "long"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "FirstName",
        "typ": {"value":  "string"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "LastName",
        "typ": {"value":  "string"},
        "position": 2,
        "sensitive": true
      },
      {
        "name": "Timestamp",
        "alias": "timeStamp_alias",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 5,
        "sensitive": false
      },
      {
        "name": "Age",
        "typ": {"value":  "integer"},
        "position": 2,
        "sensitive": true
      },
      {
        "name": "AddressInfo",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "long"}
        },
        "position": 4,
        "isPrimaryKey": false,
        "isTimestamp": false,
        "sensitive": true
      },
      {
        "name": "City",
        "typ": {"value":  "struct"},
        "sensitive": false
      },
      {
        "name": "Country",
        "typ": {"value":  "string"},
        "parentName": "City",
        "sensitive": false
      },
      {
        "name": "Region",
        "typ": {"value":  "struct"},
        "parentName": "City",
        "sensitive": false
      },
      {
        "name": "Number",
        "typ": {"value":  "long"},
        "parentName": "Region",
        "sensitive": true
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "parentName": "Region",
        "sensitive": false
      },
      {
        "name": "Street",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "integer"}
        },
        "parentName": "Region",
        "sensitive": true
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "parentName": "City",
        "sensitive": false
      },
      {
        "name": "ArrayOfArrays",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "array"}
        },
        "sensitive": true
      },
      {
        "name": "ArrayField",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "integer"}
        },
        "parentName": "ArrayOfArrays",
        "sensitive": false
      },
      {
        "name": "ArrayOfStruct",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "struct"}
        },
        "sensitive": false
      },
      {
        "name": "StructElement",
        "typ": {"value":  "struct"},
        "parentName": "ArrayOfStruct",
        "sensitive": false
      },
      {
        "name": "StructField1",
        "typ": {"value":  "string"},
        "parentName": "StructElement",
        "sensitive": true
      },
      {
        "name": "StructField2",
        "typ": {"value":  "integer"},
        "parentName": "StructElement",
        "sensitive": false
      },
      {
        "name": "ArrayOfArraysOfStruct",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "array"}
        },
        "sensitive": false
      },
      {
        "name": "ArrayOfArrayElement",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "struct"}
        },
        "parentName": "ArrayOfArraysOfStruct",
        "sensitive": false
      },
      {
        "name": "StructElement_new",
        "typ": {"value":  "struct"},
        "parentName": "ArrayOfArrayElement",
        "sensitive": false
      },
      {
        "name": "StructField1_1",
        "typ": {"value":  "string"},
        "parentName": "StructElement_new",
        "sensitive": false
      },
      {
        "name": "StructField2_1",
        "typ": {"value":  "integer"},
        "parentName": "StructElement_new",
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source1/dataset-sensitive-validator/dataset-full-snapshot-worldcities-sensitive-validator-3.json
{
  "name": "full-snapshot-worldcities-sensitive-validator-3",
  "description": "Dataset Full Snapshot World Cities Sensitive Validator",
  "sourceName": "source1",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "incremental" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database1",
  "table": "full_snapshot_worldcities_sensitive_validator_3",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "tableInput":{
    "table": "full_snapshot_worldcities_sensitive_validator_3",
    "schema": "database1",
    "query": "select * from database1.full_snapshot_worldcities_sensitive_validator_3 where ModifiedDate > to_timestamp('asdf', 'yyyy-MM-dd HH:mm:ss.SSS')",
    "onlyNewData": true
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": true
      },
      {
        "name": "country",
        "alias": "country_alias",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": true
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "geonameid",
        "alias": "geonameid_alias",
        "typ": {"value":  "long"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 4,
        "sensitive": true
      },
      {
        "name": "timeStamp",
        "alias": "timeStamp_alias",
        "typ": {"value":  "integer"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "isPartitionable": true,
        "position": 5,
        "sensitive": true,
        "transformation" : {
          "typ": {"value": "date"},
          "pattern": "yyyy-MM-dd HH:mm:ss"
        }
      },
      {
        "name": "city",
        "typ": {"value":  "struct"},
        "position": 6,
        "sensitive": false
      },
      {
        "name": "address",
        "typ": {"value":  "string"},
        "position": 7,
        "sensitive": true,
        "parentName": "city"
      }
    ]
  },
  "qualityRules": {
    "mode": { "value": "reject" },
    "uniquenessRule": {
      "rules": [
        {
          "name": "uniqueRule1",
          "columns": ["name","country"]
        }
      ]
    },
    "notNullRule": ["country"],
    "integrityRule": {
      "rules": [
        {
          "name": "Integrity1",
          "localColumns": ["country"],
          "referencedTable": "database1.last_changes_worldcities",
          "referencedColumns": ["country"]
        }
      ]},
    "expressionRule": {
      "rules": [
        {
          "name": "expr1",
          "expr": "geonameid >= 1"
        }
      ]
    }
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source3/dataset-full-failfast-worldcities-subset-parquet/dataset-full-failfast-worldcities-subset-parquet.json
{
  "name": "full-snapshot-worldcities-subset-parquet",
  "description": "Dataset Full Snapshot World Cities",
  "sourceName": "source3",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database3",
  "table": "full_snapshot_worldcities_subset_parquet",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "parquet" },
    "filePattern": "<yyyy><mm><dd>_worldCities_name.gz.parquet"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "country",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "geonameid",
        "typ": {"value":  "long"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-sqlserver/dataset-sqlserver/dataset-sqlserver-incremental.json
{
  "name": "dataset-sqlserver-incremental",
  "description": "dataset sqlserver incremental",
  "sourceName": "source-sqlserver",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "incremental" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "Production",
  "table": "ProductCategoryI",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "tableInput":{
    "table": "ProductCategoryIncremental",
    "schema": "Production"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "ProductCategoryID",
        "typ": {"value":  "integer"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "rowguid",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "ModifiedDate",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-sqlserver/dataset-sqlserver/dataset-sqlserver-fullsnapshot.json
{
  "name": "dataset-sqlserver-fullsnapshot",
  "description": "dataset sqlserver full snapshot",
  "sourceName": "source-sqlserver",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "Production",
  "table": "ProductCategoryFS",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "tableInput":{
    "table": "ProductCategory",
    "schema": "Production"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "ProductCategoryID",
        "typ": {"value":  "integer"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "rowguid",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "ModifiedDate",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-sqlserver/dataset-sqlserver/dataset-sqlserver-lastchanges.json
{
  "name": "dataset-sqlserver-lastchanges",
  "description": "dataset sqlserver lastchanges",
  "sourceName": "source-sqlserver",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "last_changes" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "Production",
  "table": "ProductCategoryLC",
  "partitionBy": "ProductCategoryID",
  "allowPartitionChange": false,
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "tableInput":{
    "table": "ProductCategoryLastChanges",
    "schema": "Production"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "ProductCategoryID",
        "typ": {"value":  "integer"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "rowguid",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "ModifiedDate",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}
