=== AlejandroAlcaraz32/MotorIndationIber/maven/src/main/resources/jsonSchemaFiles/schema-dataset.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1646063812.json",
  "title": "Root",
  "type": "object",
  "required": [
    "name",
    "description",
    "sourceName",
    "typ",
    "version",
    "enabled",
    "ingestionMode",
    "validationMode",
    "createDatabase",
    "classification",
    "database",
    "table",
    "partitionBy",
    "permissiveThresholdType",
    "permissiveThreshold",
    "schemaDefinition"

  ],
  "properties": {
    "datasetId": {
      "$id": "#root/datasetId",
      "title": "Datasetid",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "sourceId": {
      "$id": "#root/sourceId",
      "title": "sourceId",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "specificationId": {
      "$id": "#root/specificationId",
      "title": "specificationId",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "name": {
      "$id": "#root/name",
      "title": "Name",
      "type": "string",
      "default": "",
      "examples": [
        "dataset1"
      ],
      "pattern": "^.*$"
    },
    "description": {
      "$id": "#root/description",
      "title": "Description",
      "type": "string",
      "default": "",
      "examples": [
        "Dataset 1"
      ],
      "pattern": "^.*$"
    },
    "sourceName": {
      "$id": "#root/sourceName",
      "title": "Sourcename",
      "type": "string",
      "default": "",
      "examples": [
        "source1"
      ],
      "pattern": "^.*$"
    },
    "typ": {
      "$id": "#root/typ",
      "title": "Typ",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "fileInput": {
      "$id": "#root/fileInput",
      "title": "Fileinput",
      "type": "object",
      "required": [
        "format",
        "filePattern"
      ]
    },
    "kafkaInput": {
      "$id": "#root/kafkaInput",
      "title": "Kafkainput",
      "type": "object",
      "required": [
        "topicKey",
        "groupId",
        "jaasConfigurationKey"
      ]
    },
    "tableInput": {
      "$id": "#root/tableInput",
      "title": "Tableinput",
      "type": "object",
      "required": [
        "table"
      ]
    },
    "apiInput": {
      "$id": "#root/apiInput",
      "title": "APIinput",
      "type": "object",
      "required": [
        "endpoint",
        "pagination"
      ]
    },
    "version": {
      "$id": "#root/version",
      "title": "Version",
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "enabled": {
      "$id": "#root/enabled",
      "title": "Enabled",
      "type": "boolean",
      "examples": [
        true
      ],
      "default": true
    },
    "effectiveDate": {
      "$id": "#root/effectiveDate",
      "title": "Effectivedate",
      "type": "string",
      "default": "",
      "examples": [
        "2020-07-03 10:10:00"
      ],
      "pattern": "^.*$"
    },
    "ingestionMode": {
      "$id": "#root/ingestionMode",
      "title": "Ingestionmode",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "validationMode": {
      "$id": "#root/validationMode",
      "title": "Validationmode",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "createDatabase": {
      "$id": "#root/createDatabase",
      "title": "Createdatabase",
      "type": "boolean",
      "examples": [
        false
      ],
      "default": true
    },
    "classification": {
      "$id": "#root/classification",
      "title": "Classification",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "database": {
      "$id": "#root/database",
      "title": "Database",
      "type": "string",
      "default": "",
      "examples": [
        "database1"
      ],
      "pattern": "^.*$"
    },
    "table": {
      "$id": "#root/table",
      "title": "Table",
      "type": "string",
      "default": "",
      "examples": [
        "table1"
      ],
      "pattern": "^.*$"
    },
    "partitionBy": {
      "$id": "#root/partitionBy",
      "title": "Partitionby",
      "type": "string",
      "default": "",
      "examples": [
        "yyyy/mm/dd"
      ],
      "pattern": "^.*$"
    },
    "allowPartitionChange": {
      "$id": "#root/allowPartitionChange",
      "title": "Allowpartitionchange",
      "type": "boolean",
      "examples": [
        false
      ],
      "default": true
    },
    "permissiveThresholdType": {
      "$id": "#root/permissiveThresholdType",
      "title": "Permissivethresholdtype",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "permissiveThreshold": {
      "$id": "#root/permissiveThreshold",
      "title": "Permissivethreshold",
      "type": "integer",
      "examples": [
        10
      ],
      "default": 0
    },
    "schemaDefinition": {
      "$id": "#root/schemaDefinition",
      "title": "Schemadefinition",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "schemaFile": {
      "$id": "#root/schemaFile",
      "title": "Schemafile",
      "type": "string",
      "default": "",
      "examples": [
        "/source1/dataset1/avro-schema.json"
      ],
      "pattern": "^.*$"
    },
    "schemaColumns": {
      "$id": "#root/schemaColumns",
      "title": "Schemacolumns",
      "type": "object",
      "required": [
        "columns"
      ]
    },
    "schemaJson": {
      "$id": "#root/schemaJson",
      "title": "Schemajson",
      "type": "object",
      "required": [
        "type",
        "fields"
      ]
    },
    "qualityRules": {
      "$id": "#root/qualityRules",
      "title": "Qualityrules",
      "type": "object",
      "required": [
        "mode"
      ]
    }
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/dimensiones/slv_personas/dataset-dim_mando.json
{
  "name": "dim_mando",
  "description": "",
  "sourceName": "dimensiones",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "slv_personas",
  "table": "dim_mando",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "csv" },
    "filePattern": "MANDOS.csv",
    "csv": {
      "charset": "UTF-8",
      "header": { "value": "first_line"},
      "delimiter":  ";"
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "Puestos",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Equipo_a_cargo",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "Puesto_con_Responsabilidad",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "Mando",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/dimensiones/slv_personas/dataset-dim_empleado.json
{
	"name": "dim_empleado",
	"description": "",
	"sourceName": "dimensiones",
	"typ": {
		"value": "file"
	},
	"version": 1,
	"enabled": true,
	"classification": {
		"value": "public"
	},
	"effectiveDate": "2020-07-03 10:10:00",
	"ingestionMode": {
		"value": "full_snapshot"
	},
	"validationMode": {
		"value": "fail_fast"
	},
	"createDatabase": true,
	"database": "slv_personas",
	"table": "dim_empleado",
	"partitionBy": "",
	"permissiveThresholdType": {
		"value": "absolute"
	},
	"permissiveThreshold": 10,
	"fileInput": {
		"format": {
			"value": "csv"
		},
		"filePattern": "BBDD_MVPTRAVEL.csv",
		"csv": {
			"charset": "UTF-16",
			"header": {
				"value": "without_header"
			},
			"delimiter": ";",
			"lineSep": "\r"
		}
	},
	"schemaDefinition": {
		"value": "json-columns"
	},
	"schemaFile": "",
	"schemaColumns": {
		"columns": [
			{
				"name": "email",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 1,
				"sensitive": false
			},
			{
				"name": "id_trabajador",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 2,
				"sensitive": false
			},
			{
				"name": "apellidos",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 3,
				"sensitive": false
			},
			{
				"name": "nombre",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 4,
				"sensitive": false
			},
			{
				"name": "nomenclatura_firma",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 5,
				"sensitive": false
			},
			{
				"name": "departamento_firma",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 6,
				"sensitive": false
			},
			{
				"name": "empresa",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 7,
				"sensitive": false
			},
			{
				"name": "centro_trabajo_desc",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 8,
				"sensitive": false
			},
			{
				"name": "departamento",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 9,
				"sensitive": false
			},
			{
				"name": "area",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 10,
				"sensitive": false
			},
			{
				"name": "subarea",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 11,
				"sensitive": false
			},
			{
				"name": "atributo_direccion",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 12,
				"sensitive": false
			},
			{
				"name": "atributo_1_vertical-3_transversal-refacturacion",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 13,
				"sensitive": false
			},
			{
				"name": "responsable_1",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 14,
				"sensitive": false
			},
			{
				"name": "usr_puesto_trabajo",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 15,
				"sensitive": false
			},
			{
				"name": "cambios_temporales",
				"typ": {
					"value": "string"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 16,
				"sensitive": false
			},
			{
				"name": "fecha",
				"typ": {
					"value": "date"
				},
				"isPrimaryKey": false,
				"isTimestamp": false,
				"position": 17,
				"sensitive": false,
				"transformation": {
					"typ": {
						"value": "date"
					},
					"pattern": "dd/MM/yyyy"
				}
			}
		]
	}
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-api/dataset-api-json-columns/dataset-api-json-columns-3.json
{
  "name": "dataset-api-json-columns-3",
  "description": "dataset api json columns 3",
  "sourceName": "source-api",
  "typ": { "value": "api" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "incremental" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database_api",
  "table": "jsoncolumns_3",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "apiInput":{
    "endpoint": "People",
    "parameters": "$filter=UserName+eq+'{lastValue}'",
    "pagination": {
      "typ": {"value" :"offset"},
      "top": "$top",
      "skip": "$skip",
      "topSize": 10
    },
    "dataIn": "value",
    "headers": {
      "content-type": "json"
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "/source-api/dataset-api-full/dataset-api-fullsnapshot_schema.json",
  "schemaColumns": {
    "columns": [
      {
        "name": "UserName",
        "typ": {"value":  "string"},
        "isPrimaryKey": true,
        "isTimestamp": true,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Concurrency",
        "typ": {"value":  "long"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "FirstName",
        "typ": {"value":  "string"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "LastName",
        "typ": {"value":  "string"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "Gender",
        "typ": {"value":  "string"},
        "position": 3,
        "sensitive": false
      },
      {
        "name": "Emails",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "string"}
        },
        "position": 4,
        "isPrimaryKey": false,
        "isTimestamp": false,
        "sensitive": false
      },
      {
        "name": "AddressInfo",
        "typ": {"value":  "struct"},
        "position": 4,
        "isPrimaryKey": false,
        "isTimestamp": false,
        "sensitive": false
      },
      {
        "name": "Address",
        "typ": {"value":  "string"},
        "parentName": "AddressInfo",
        "sensitive": false
      },
      {
        "name": "City",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "string"}
        },
        "parentName": "AddressInfo",
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-sqlserver/dataset-sqlserver/dataset-sqlserver-fullsnapshot-date.json
{
  "name": "dataset-sqlserver-fullsnapshot-date",
  "description": "dataset sqlserver full snapshot with date and datetime",
  "sourceName": "source-sqlserver",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-01-01 00:00:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "Sales",
  "table": "SalesOrderDay",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 0,
  "tableInput":{
    "table": "SalesOrderDay",
    "schema": "Sales"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "typ": { "value": "integer"},
        "name": "SalesOrderID",
        "description": "SalesOrderID",
        "position": 1,
        "dictionaryLinkedName": "",
        "isPrimaryKey": false,
        "isTimestamp": false,
        "isPartitionable": false,
        "sensitive": false
      }
    ,{
        "typ": { "value": "datetime"},
        "name": "OrderDate",
        "description": "OrderDate",
        "position": 2,
        "dictionaryLinkedName": "",
        "isPrimaryKey": false,
        "isTimestamp": false,
        "isPartitionable": false,
        "sensitive": false
      }
    ,{
        "typ": { "value": "date"},
        "name": "OrderDay",
        "description": "OrderDay",
        "position": 3,
        "dictionaryLinkedName": "",
        "isPrimaryKey": false,
        "isTimestamp": false,
        "isPartitionable": false,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-excel-6/dataset-incremental-worldcities/dataset-incremental-evo-worldcities.json
{
  "name": "incremental-worldcities",
  "description": "Dataset incremental world cities",
  "sourceName": "source-excel-6",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "incremental" },
  "validationMode": { "value": "permissive" },
  "createDatabase": true,
  "database": "database6",
  "table": "incremental_worldcities",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"percentage"},
  "permissiveThreshold": 20,
  "fileInput":{
    "format": { "value": "xls" },
    "filePattern": "<yyyy><mm><dd>_incremental_evo_worldCities.xls",
    "xls": {
      "header": { "value": "first_line"},
      "dataRange": "A1"
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "country",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "geonameid",
        "typ": {"value":  "long"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      },
      {
        "name": "timeStamp",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 5,
        "sensitive": false,
        "transformation" : {
          "typ": {"value": "date"},
          "pattern": "yyyy-MM-dd HH:mm:ss"
        }
      },
      {
        "name": "evo1",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 6,
        "sensitive": false
      },
      {
        "name": "geonameid2",
        "typ": {"value":  "long"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 7,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source4/dataset-full-failfast-worldcities-subset-orc/dataset-full-failfast-worldcities-subset-orc.json
{
  "name": "full-snapshot-worldcities-subset-orc",
  "description": "Dataset Full Snapshot World Cities",
  "sourceName": "source4",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database4",
  "table": "full_snapshot_worldcities_subset_orc",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "orc" },
    "filePattern": "<yyyy><mm><dd>_worldCities.zlib.orc"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "country",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "geonameid",
        "typ": {"value":  "long"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-json-5/dataset-json-last-changes-failfast-worldcities/dataset-last-changes-failfast-worldcities-json.json
{
  "name": "last-changes-worldcities-json",
  "description": "Dataset Last Changes World Cities",
  "sourceName": "source-json-5",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "last_changes" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database5",
  "table": "last_changes_worldcities_json",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "json" },
    "json": {
      "encoding": "UTF-8",
      "multiline": false,
      "allowUnquotedFieldNames": false,
      "allowNumericLeadingZeros": false
    },
    "filePattern": "<yyyy><mm><dd>_last_changes_worldCities.json"
  },
  "schemaDefinition": {"value": "json-schema"},
  "schemaJson": {
    "type": "struct",
    "fields": [
      {
        "name": "name",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "country",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "subcountry",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "geonameid",
        "type": "long",
        "nullable": true,
        "metadata": {
          "isPrimaryKey": true
        }
      },
      {
        "name": "timeStamp",
        "type": "timestamp",
        "nullable": true,
        "metadata": {
          "isTimestamp": true
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source2/dataset-full-failfast-worldcities-subset-avro/dataset-full-failfast-worldcities-subset-avro.json
{
  "name": "full-snapshot-worldcities-subset-avro",
  "description": "Dataset Full Snapshot World Cities",
  "sourceName": "source2",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database2",
  "table": "full_snapshot_worldcities_subset_avro",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "avro" },
    "filePattern": "<yyyy><mm><dd>_worldCities_subset.bz2.avro"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "country",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "geonameid",
        "typ": {"value":  "long"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}
