=== AlejandroAlcaraz32/MotorIndationIber/maven/src/main/resources/jsonSchemaFiles/schema-transformation.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1646304969.json",
  "title": "Root",
  "type": "object",
  "required": [
    "name",
    "description",
    "typ"
  ],
  "properties": {
    "name": {
      "$id": "#root/name",
      "title": "Name",
      "type": "string",
      "default": "",
      "examples": [
        "transform-testMLTrans3"
      ],
      "pattern": "^.*$"
    },
    "description": {
      "$id": "#root/description",
      "title": "Description",
      "type": "string",
      "default": "",
      "examples": [
        "Read table from silver"
      ],
      "pattern": "^.*$"
    },
    "typ": {
      "$id": "#root/typ",
      "title": "Typ",
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "$id": "#root/typ/value",
          "title": "Value",
          "type": "string",
          "default": "",
          "examples": [
            "datalake"
          ],
          "pattern": "^.*$"
        }
      }
    },
    "sqlTransformation": {
      "$id": "#root/sqlTransformation",
      "title": "Sqltransformation",
      "type": "object",
      "required": [
        "sourceTables",
        "stages"
      ],
      "properties": {
        "sourceTables": {
          "$id": "#root/sqlTransformation/sourceTables",
          "title": "Sourcetables",
          "type": "array",
          "default": [],
          "items": {
            "$id": "#root/sqlTransformation/sourceTables/items",
            "title": "Items",
            "type": "object",
            "required": [
              "sqlConnection",
              "sqlSchema",
              "sqlTable",
              "sqlWriteMode",
              "cleanAfter",
              "dropAfter"
            ],
            "properties": {
              "dlkClassification": {
                "$id": "#root/sqlTransformation/sourceTables/items/dlkClassification",
                "title": "Dlkclassification",
                "type": "string",
                "default": "",
                "examples": [
                  "public"
                ],
                "pattern": "^.*$"
              },
              "dlkDatabase": {
                "$id": "#root/sqlTransformation/sourceTables/items/dlkDatabase",
                "title": "Dlkdatabase",
                "type": "string",
                "default": "",
                "examples": [
                  "eas-sdb-gld-kpi-operaciones"
                ],
                "pattern": "^.*$"
              },
              "dlkTable": {
                "$id": "#root/sqlTransformation/sourceTables/items/dlkTable",
                "title": "Dlktable",
                "type": "string",
                "default": "",
                "examples": [
                  "demotransformacion"
                ],
                "pattern": "^.*$"
              },
              "sqlConnection": {
                "$id": "#root/sqlTransformation/sourceTables/items/sqlConnection",
                "title": "Sqlconnection",
                "type": "string",
                "default": "",
                "examples": [
                  "eas-sdb-gld-kpi-operaciones"
                ],
                "pattern": "^.*$"
              },
              "sqlSchema": {
                "$id": "#root/sqlTransformation/sourceTables/items/sqlSchema",
                "title": "Sqlschema",
                "type": "string",
                "default": "",
                "examples": [
                  "datamart"
                ],
                "pattern": "^.*$"
              },
              "sqlTable": {
                "$id": "#root/sqlTransformation/sourceTables/items/sqlTable",
                "title": "Sqltable",
                "type": "string",
                "default": "",
                "examples": [
                  "demotransformacion_sql"
                ],
                "pattern": "^.*$"
              },
              "sqlWriteMode": {
                "$id": "#root/sqlTransformation/sourceTables/items/sqlWriteMode",
                "title": "Sqlwritemode",
                "type": "object",
                "required": [
                  "value"
                ],
                "properties": {
                  "value": {
                    "$id": "#root/sqlTransformation/sourceTables/items/sqlWriteMode/value",
                    "title": "Value",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "overwrite"
                    ],
                    "pattern": "^.*$"
                  }
                }
              },
              "cleanAfter": {
                "$id": "#root/sqlTransformation/sourceTables/items/cleanAfter",
                "title": "Cleanafter",
                "type": "boolean",
                "examples": [
                  false
                ],
                "default": true
              },
              "dropAfter": {
                "$id": "#root/sqlTransformation/sourceTables/items/dropAfter",
                "title": "Dropafter",
                "type": "boolean",
                "examples": [
                  false
                ],
                "default": true
              }
            }
          }
        },
        "stages": {
          "$id": "#root/sqlTransformation/stages",
          "title": "Stages",
          "type": "array",
          "default": []
        }
      }
    },
    "datalakeTransformation": {
      "$id": "#root/datalakeTransformation",
      "title": "Datalaketransformation",
      "type": "object",
      "required": [
        "classification",
        "database",
        "table",
        "mode",
        "stages"
      ],
      "properties": {
        "classification": {
          "$id": "#root/datalakeTransformation/classification",
          "title": "Classification",
          "type": "string",
          "default": "",
          "examples": [
            "featureengine"
          ],
          "pattern": "^.*$"
        },
        "database": {
          "$id": "#root/datalakeTransformation/database",
          "title": "Database",
          "type": "string",
          "default": "",
          "examples": [
            "data_output"
          ],
          "pattern": "^.*$"
        },
        "table": {
          "$id": "#root/datalakeTransformation/table",
          "title": "Table",
          "type": "string",
          "default": "",
          "examples": [
            "test_2"
          ],
          "pattern": "^.*$"
        },
        "partition": {
          "$id": "#root/datalakeTransformation/partition",
          "title": "Partition",
          "type": "string",
          "default": "",
          "examples": [
            ""
          ],
          "pattern": "^.*$"
        },
        "mode": {
          "$id": "#root/datalakeTransformation/mode",
          "title": "Mode",
          "type": "object",
          "required": [
            "value"
          ],
          "properties": {
            "value": {
              "$id": "#root/datalakeTransformation/mode/value",
              "title": "Value",
              "type": "string",
              "default": "",
              "examples": [
                "overwrite"
              ],
              "pattern": "^.*$"
            }
          }
        },
        "stages": {
          "$id": "#root/datalakeTransformation/stages",
          "title": "Stages",
          "type": "array",
          "default": [],
          "items": {
            "$id": "#root/datalakeTransformation/stages/items",
            "title": "Items",
            "type": "object",
            "required": [
              "name",
              "description",
              "typ"
            ],
            "properties": {
              "name": {
                "$id": "#root/datalakeTransformation/stages/items/name",
                "title": "Name",
                "type": "string",
                "default": "",
                "examples": [
                  "stage table 1"
                ],
                "pattern": "^.*$"
              },
              "description": {
                "$id": "#root/datalakeTransformation/stages/items/description",
                "title": "Description",
                "type": "string",
                "default": "",
                "examples": [
                  "stage 1"
                ],
                "pattern": "^.*$"
              },
              "typ": {
                "$id": "#root/datalakeTransformation/stages/items/typ",
                "title": "Typ",
                "type": "object",
                "required": [
                  "value"
                ],
                "properties": {
                  "value": {
                    "$id": "#root/datalakeTransformation/stages/items/typ/value",
                    "title": "Value",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "table"
                    ],
                    "pattern": "^.*$"
                  }
                }
              },
              "stageTable": {
                "$id": "#root/datalakeTransformation/stages/items/stageTable",
                "title": "Stagetable",
                "type": "object",
                "required": [
                  "name",
                  "typ",
                  "table"
                ],
                "properties": {
                  "name": {
                    "$id": "#root/datalakeTransformation/stages/items/stageTable/name",
                    "title": "Name",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "data"
                    ],
                    "pattern": "^.*$"
                  },
                  "typ": {
                    "$id": "#root/datalakeTransformation/stages/items/stageTable/typ",
                    "title": "Typ",
                    "type": "object",
                    "required": [
                      "value"
                    ],
                    "properties": {
                      "value": {
                        "$id": "#root/datalakeTransformation/stages/items/stageTable/typ/value",
                        "title": "Value",
                        "type": "string",
                        "default": "",
                        "examples": [
                          "test"
                        ],
                        "pattern": "^.*$"
                      }
                    }
                  },
                  "database": {
                    "$id": "#root/datalakeTransformation/stages/items/stageTable/database",
                    "title": "Database",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "origin"
                    ],
                    "pattern": "^.*$"
                  },
                  "table": {
                    "$id": "#root/datalakeTransformation/stages/items/stageTable/table",
                    "title": "Table",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "data"
                    ],
                    "pattern": "^.*$"
                  }
                }
              }
            }
          }
        },
        "qualityRules": {
          "$id": "#root/datalakeTransformation/qualityRules",
          "title": "Qualityrules",
          "type": "object",
          "required": [
          ],
          "properties": {
            "uniquenessRule": {
              "$id": "#root/datalakeTransformation/qualityRules/uniquenessRule",
              "title": "Uniquenessrule",
              "type": "object",
              "required": [
                "rules"
              ],
              "properties": {
                "rules": {
                  "$id": "#root/datalakeTransformation/qualityRules/uniquenessRule/rules",
                  "title": "Rules",
                  "type": "array",
                  "default": [],
                  "items": {
                    "$id": "#root/datalakeTransformation/qualityRules/uniquenessRule/rules/items",
                    "title": "Items",
                    "type": "object",
                    "required": [
                      "name",
                      "columns"
                    ],
                    "properties": {
                      "name": {
                        "$id": "#root/datalakeTransformation/qualityRules/uniquenessRule/rules/items/name",
                        "title": "Name",
                        "type": "string",
                        "default": "",
                        "examples": [
                          "uniquenessrule1"
                        ],
                        "pattern": "^.*$"
                      },
                      "columns": {
                        "$id": "#root/datalakeTransformation/qualityRules/uniquenessRule/rules/items/columns",
                        "title": "Columns",
                        "type": "array",
                        "default": [],
                        "items": {
                          "$id": "#root/datalakeTransformation/qualityRules/uniquenessRule/rules/items/columns/items",
                          "title": "Items",
                          "type": "string",
                          "default": "",
                          "examples": [
                            "EnglishProductCategoryName"
                          ],
                          "pattern": "^.*$"
                        }
                      }
                    }
                  }

                }
              }
            },
            "notNullRule": {
              "$id": "#root/datalakeTransformation/qualityRules/notNullRule",
              "title": "Notnullrule",
              "type": "array",
              "default": [],
              "items": {
                "$id": "#root/datalakeTransformation/qualityRules/notNullRule/items",
                "title": "Items",
                "type": "string",
                "default": "",
                "examples": [
                  "EnglishProductCategoryName"
                ],
                "pattern": "^.*$"
              }
            },
            "integrityRule": {
              "$id": "#root/datalakeTransformation/qualityRules/integrityRule",
              "title": "Integrityrule",
              "type": "object",
              "required": [
                "rules"
              ],
              "properties": {
                "rules": {
                  "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules",
                  "title": "Rules",
                  "type": "array",
                  "default": [],
                  "items": {
                    "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules/items",
                    "title": "Items",
                    "type": "object",
                    "required": [
                      "name",
                      "localColumns",
                      "referencedTable",
                      "referencedColumns"
                    ],
                    "properties": {
                      "name": {
                        "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules/items/name",
                        "title": "Name",
                        "type": "string",
                        "default": "",
                        "examples": [
                          "Integrity1"
                        ],
                        "pattern": "^.*$"
                      },
                      "localColumns": {
                        "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules/items/localColumns",
                        "title": "Localcolumns",
                        "type": "array",
                        "default": [],
                        "items": {
                          "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules/items/localColumns/items",
                          "title": "Items",
                          "type": "string",
                          "default": "",
                          "examples": [
                            "country"
                          ],
                          "pattern": "^.*$"
                        }
                      },
                      "referencedTable": {
                        "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules/items/referencedTable",
                        "title": "Referencedtable",
                        "type": "string",
                        "default": "",
                        "examples": [
                          "database1.last_changes_worldcities"
                        ],
                        "pattern": "^.*$"
                      },
                      "referencedColumns": {
                        "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules/items/referencedColumns",
                        "title": "Referencedcolumns",
                        "type": "array",
                        "default": [],
                        "items": {
                          "$id": "#root/datalakeTransformation/qualityRules/integrityRule/rules/items/referencedColumns/items",
                          "title": "Items",
                          "type": "string",
                          "default": "",
                          "examples": [
                            "country"
                          ],
                          "pattern": "^.*$"
                        }
                      }
                    }
                  }

                }
              }
            },
            "expressionRule": {
              "$id": "#root/datalakeTransformation/qualityRules/expressionRule",
              "title": "Expressionrule",
              "type": "object",
              "required": [
                "rules"
              ],
              "properties": {
                "rules": {
                  "$id": "#root/datalakeTransformation/qualityRules/expressionRule/rules",
                  "title": "Rules",
                  "type": "array",
                  "default": [],
                  "items": {
                    "$id": "#root/datalakeTransformation/qualityRules/expressionRule/rules/items",
                    "title": "Items",
                    "type": "object",
                    "required": [
                      "name",
                      "expr"
                    ],
                    "properties": {
                      "name": {
                        "$id": "#root/datalakeTransformation/qualityRules/expressionRule/rules/items/name",
                        "title": "Name",
                        "type": "string",
                        "default": "",
                        "examples": [
                          "exprRule1"
                        ],
                        "pattern": "^.*$"
                      },
                      "expr": {
                        "$id": "#root/datalakeTransformation/qualityRules/expressionRule/rules/items/expr",
                        "title": "Expr",
                        "type": "string",
                        "default": "",
                        "examples": [
                          "ProductCategoryKey > 1"
                        ],
                        "pattern": "^.*$"
                      }
                    }
                  }

                }
              }
            }

          }
        }
      }
    }
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metagold/metadata/transformations/transform-plain-product-sql.json
{
  "name": "plain-product-sql",
  "description":"product joined with category and subcategory",
  "typ": {"value":  "sql"},
  "sqlTransformation":
  {
    "sourceTables": [
      {
        "dlkClassification": "public",
        "dlkDatabase": "production",
        "dlkTable": "category",
        "dlkFilterExpr": "ProductCategoryKey <= 3",
        "sqlConnection": "testConnection",
        "sqlSchema": "staging",
        "sqlTable": "category",
        "sqlWriteMode": {"value":  "append"},
        "cleanAfter": false,
        "dropAfter": true
      },
      {
        "dlkSQL": "select ProductName, sum, sumDistinct, count from vw_result",
        "sqlConnection": "testConnectionUrl",
        "sqlSchema": "staging",
        "sqlTable": "product_subcategory",
        "sqlWriteMode": {"value":  "overwrite"},
        "cleanAfter": true,
        "dropAfter": false
      },
      {
        "dlkClassification": "public",
        "dlkDatabase": "production",
        "dlkTable": "category",
        "sqlConnection": "testConnection",
        "sqlSchema": "staging",
        "sqlTable": "category2",
        "sqlWriteMode": {"value":  "truncate"},
        "cleanAfter": false,
        "dropAfter": false,
        "deleteAfterWhere": "ProductCategoryKey <= 3"
      }
    ],
    "stages": [
      {
        "connection": "testConnection",
        "destSchema": "datamart",
        "destTable": "plainProduct",
        "sqlSelectExpr": "select * from staging.product_subcategory",
        "writeMode": {"value":  "truncate"},
        "cleanAfter": true,
        "dropAfter": false
      },
      {
        "connection": "testConnection",
        "destSchema": "datamart",
        "destTable": "category",
        "sqlSelectExpr": "select * from staging.category",
        "filterExpr": "paramCategory = ProductCategoryKey",
        "writeMode": {"value":  "overwrite"},
        "cleanAfter": false,
        "dropAfter": true
      },
      {
        "connection": "testConnection",
        "destSchema": "datamart",
        "destTable": "aggProduct",
        "sqlSelectExpr": "select ProductName, count(*) total from datamart.category cross join datamart.plainProduct group by ProductName",
        "writeMode": {"value":  "overwrite"},
        "cleanAfter": false,
        "dropAfter": false

      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metagold/metadata/transformations/transform-testMLTrans5.json
{
  "name": "transform-testMLTrans5",
  "description":"Read table from silver",
  "typ": {"value":  "datalake"},
  "datalakeTransformation":
  {
    "classification": "featureengine",
    "database": "data_output",
    "table": "test_4",
    "partition": "",
    "mode": {"value":  "overwrite"},
    "stages": [
      {
        "name": "stage table 1",
        "description": "stage 1",
        "typ": {"value":  "table"},
        "stageTable": {
          "name": "data",
          "typ": {"value":  "test"},
          "database": "origin",
          "table": "data"
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metagold/metadata/transformations/transform-testMLTrans2.json
{
  "name": "transform-testMLTrans2",
  "description":"Read table from silver",
  "typ": {"value":  "datalake"},
  "datalakeTransformation":
  {
    "classification": "featureengine",
    "database": "data_output",
    "table": "test_1b",
    "partition": "",
    "mode": {"value":  "overwrite"},
    "stages": [
      {
        "name": "stage table 1",
        "description": "stage 1",
        "typ": {"value":  "table"},
        "stageTable": {
          "name": "data",
          "typ": {"value":  "test"},
          "database": "origin",
          "table": "data"
        }
      },
      {
        "name": "stage select",
        "description": "stage 2",
        "typ": {"value":  "select"},
        "stageSelect": [
          {
            "columnName": "int",
            "columnDescription": "int",
            "columnAlias": "int_v2"
          },
          {
            "columnName": "double",
            "columnDescription": "double",
            "columnAlias": "double_v2"
          },
          {
            "columnName": "array",
            "columnDescription": "array",
            "columnAlias": "array_v2"
          }
        ]
      },
      {
        "name": "stage table 2 join",
        "description": "stage 2",
        "typ": {"value":  "table"},
        "stageTable": {
          "name": "data_join",
          "typ": {"value":  "test"},
          "database": "origin",
          "table": "data_join",
          "joinExpr": {
            "typ": {"value":  "inner"},
            "expr": "index = data_join.index"
          }
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metagold/metadata/transformations/dependencies/transform-two-dlk.json
{
  "name": "two-dlk",
  "description":"Bring product category from silver. Simple full copy",
  "typ": {"value":  "datalake"},
  "datalakeTransformation":
  {
    "classification": "public",
    "database": "production",
    "table": "category2",
    "mode": {"value":  "truncate"},
    "stages": [
      {
        "name": "stage bring category from silver",
        "description": "stage 1",
        "typ": {"value":  "table"},
        "stageTable": {
          "name": "DimProductCategory",
          "typ": {"value":  "silver"},
          "database": "database",
          "table": "DimProductCategory"
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metagold/metadata/transformations/transform-testMLTrans6.json
{
  "name": "transform-testMLTrans6",
  "description":"Read table from silver",
  "typ": {"value":  "datalake"},
  "datalakeTransformation":
  {
    "classification": "featureengine",
    "database": "data_output",
    "table": "test_5",
    "partition": "",
    "mode": {"value":  "overwrite"},
    "stages": [
      {
        "name": "stage table 1",
        "description": "stage 1",
        "typ": {"value":  "table"},
        "stageTable": {
          "name": "data",
          "typ": {"value":  "test"},
          "database": "origin",
          "table": "data"
        }
      },
      {
        "name": "stage fill na",
        "description": "stage 2",
        "typ": {"value":  "filler"},
        "drop": ["cmesano"],
        "distinct": true,
        "stageFiller": {
          "name": "fillna",
          "typ": {"value":  "int"},
          "value": "50"
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metagold/metadata/transformations/transform-testMLTrans4.json
{
  "name": "transform-testMLTrans4",
  "description":"Read table from silver",
  "typ": {"value":  "datalake"},
  "datalakeTransformation":
  {
    "classification": "featureengine",
    "database": "data_output",
    "table": "test_3",
    "partition": "",
    "mode": {"value":  "overwrite"},
    "stages": [
      {
        "name": "stage table 1",
        "description": "stage 1",
        "typ": {"value":  "table"},
        "stageTable": {
          "name": "data",
          "typ": {"value":  "test"},
          "database": "origin",
          "table": "data"
        }
      },
      {
        "name": "stage 3 one",
        "description": "stage 3",
        "typ": {"value":  "oneHotEncoder"},
        "stageOneHotEncoder": {
          "name": "one",
          "description": "Product Description",
          "typ": {"value":  "list"},
          "inputCols": ["int"],
          "outputCols": ["int_one"],
          "historicalTable":  {
            "name": "data_historica",
            "typ": {"value":  "test"},
            "database": "origin",
            "table": "data_historica"
          }
        }
      },
      {
        "name": "stage 4 imputer",
        "description": "stage 4",
        "typ": {"value":  "imputer"},
        "stageImputer": {
          "name": "imput",
          "description": "Product Description",
          "strategy": {"value" :"median"},
          "typ": {"value":  "single"},
          "inputCol": "int",
          "outputCol": "int_im",
          "historicalTable":  {
            "name": "data_historica",
            "typ": {"value":  "test"},
            "database": "origin",
            "table": "data_historica"
          }
        }
      }
    ]
  }
}
