=== AlejandroAlcaraz32/MotorIndationIber/maven/src/main/resources/jsonSchemaFiles/schema-dataset.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1646063812.json",
  "title": "Root",
  "type": "object",
  "required": [
    "name",
    "description",
    "sourceName",
    "typ",
    "version",
    "enabled",
    "ingestionMode",
    "validationMode",
    "createDatabase",
    "classification",
    "database",
    "table",
    "partitionBy",
    "permissiveThresholdType",
    "permissiveThreshold",
    "schemaDefinition"

  ],
  "properties": {
    "datasetId": {
      "$id": "#root/datasetId",
      "title": "Datasetid",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "sourceId": {
      "$id": "#root/sourceId",
      "title": "sourceId",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "specificationId": {
      "$id": "#root/specificationId",
      "title": "specificationId",
      "type": "integer",
      "default": "",
      "examples": [
        1
      ],
      "pattern": "^.*$"
    },
    "name": {
      "$id": "#root/name",
      "title": "Name",
      "type": "string",
      "default": "",
      "examples": [
        "dataset1"
      ],
      "pattern": "^.*$"
    },
    "description": {
      "$id": "#root/description",
      "title": "Description",
      "type": "string",
      "default": "",
      "examples": [
        "Dataset 1"
      ],
      "pattern": "^.*$"
    },
    "sourceName": {
      "$id": "#root/sourceName",
      "title": "Sourcename",
      "type": "string",
      "default": "",
      "examples": [
        "source1"
      ],
      "pattern": "^.*$"
    },
    "typ": {
      "$id": "#root/typ",
      "title": "Typ",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "fileInput": {
      "$id": "#root/fileInput",
      "title": "Fileinput",
      "type": "object",
      "required": [
        "format",
        "filePattern"
      ]
    },
    "kafkaInput": {
      "$id": "#root/kafkaInput",
      "title": "Kafkainput",
      "type": "object",
      "required": [
        "topicKey",
        "groupId",
        "jaasConfigurationKey"
      ]
    },
    "tableInput": {
      "$id": "#root/tableInput",
      "title": "Tableinput",
      "type": "object",
      "required": [
        "table"
      ]
    },
    "apiInput": {
      "$id": "#root/apiInput",
      "title": "APIinput",
      "type": "object",
      "required": [
        "endpoint",
        "pagination"
      ]
    },
    "version": {
      "$id": "#root/version",
      "title": "Version",
      "type": "integer",
      "examples": [
        1
      ],
      "default": 0
    },
    "enabled": {
      "$id": "#root/enabled",
      "title": "Enabled",
      "type": "boolean",
      "examples": [
        true
      ],
      "default": true
    },
    "effectiveDate": {
      "$id": "#root/effectiveDate",
      "title": "Effectivedate",
      "type": "string",
      "default": "",
      "examples": [
        "2020-07-03 10:10:00"
      ],
      "pattern": "^.*$"
    },
    "ingestionMode": {
      "$id": "#root/ingestionMode",
      "title": "Ingestionmode",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "validationMode": {
      "$id": "#root/validationMode",
      "title": "Validationmode",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "createDatabase": {
      "$id": "#root/createDatabase",
      "title": "Createdatabase",
      "type": "boolean",
      "examples": [
        false
      ],
      "default": true
    },
    "classification": {
      "$id": "#root/classification",
      "title": "Classification",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "database": {
      "$id": "#root/database",
      "title": "Database",
      "type": "string",
      "default": "",
      "examples": [
        "database1"
      ],
      "pattern": "^.*$"
    },
    "table": {
      "$id": "#root/table",
      "title": "Table",
      "type": "string",
      "default": "",
      "examples": [
        "table1"
      ],
      "pattern": "^.*$"
    },
    "partitionBy": {
      "$id": "#root/partitionBy",
      "title": "Partitionby",
      "type": "string",
      "default": "",
      "examples": [
        "yyyy/mm/dd"
      ],
      "pattern": "^.*$"
    },
    "allowPartitionChange": {
      "$id": "#root/allowPartitionChange",
      "title": "Allowpartitionchange",
      "type": "boolean",
      "examples": [
        false
      ],
      "default": true
    },
    "permissiveThresholdType": {
      "$id": "#root/permissiveThresholdType",
      "title": "Permissivethresholdtype",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "permissiveThreshold": {
      "$id": "#root/permissiveThreshold",
      "title": "Permissivethreshold",
      "type": "integer",
      "examples": [
        10
      ],
      "default": 0
    },
    "schemaDefinition": {
      "$id": "#root/schemaDefinition",
      "title": "Schemadefinition",
      "type": "object",
      "required": [
        "value"
      ]
    },
    "schemaFile": {
      "$id": "#root/schemaFile",
      "title": "Schemafile",
      "type": "string",
      "default": "",
      "examples": [
        "/source1/dataset1/avro-schema.json"
      ],
      "pattern": "^.*$"
    },
    "schemaColumns": {
      "$id": "#root/schemaColumns",
      "title": "Schemacolumns",
      "type": "object",
      "required": [
        "columns"
      ]
    },
    "schemaJson": {
      "$id": "#root/schemaJson",
      "title": "Schemajson",
      "type": "object",
      "required": [
        "type",
        "fields"
      ]
    },
    "qualityRules": {
      "$id": "#root/qualityRules",
      "title": "Qualityrules",
      "type": "object",
      "required": [
        "mode"
      ]
    }
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-sqlserver/dataset-sqlserver-full/dataset-sqlserver-fullsnapshot-partition.json
{
  "name": "dataset-sqlserver-fullsnapshot-partition1-fullsourcetest",
  "description": "dataset sqlserver full snapshot partitioned by Category first query",
  "sourceName": "source-sqlserver-full",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "Sales",
  "table": "SalesOrderPerDayFull",
  "partitionBy": "Category",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "tableInput":{
    "table": "SalesOrderPerDay",
    "query": "SELECT t2.OrderDay,t4.Name Category,cast(SUM(t1.LineTotal) as decimal(38,6)) as SumTotal FROM [Sales].[V_SalesOrderDetail] t1 INNER JOIN [Sales].[SalesOrderDay] t2 ON t1.SalesOrderID=t2.SalesOrderID INNER JOIN Production.Product t3 ON t1.ProductID=t3.ProductID INNER JOIN Production.ProductSubcategory t4 ON t4.ProductSubcategoryID=t3.ProductSubcategoryID where OrderDay = '2011-05-31' GROUP BY t2.OrderDay,t4.Name"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "OrderDay",
        "typ": {"value":  "date"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Category",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "SumTotal",
        "typ": {"value":  "decimal"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false,
        "decimalParameters": {
          "precision": 38,
          "scale": 6
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-streaming/dataset-topic/dataset-topic.json
{
  "name": "topic-worldcities",
  "description": "Dataset Topic Worlcities",
  "sourceName": "source-kafka",
  "typ": { "value": "topic" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "interno" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "incremental" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "streaming",
  "table": "worldcities",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "kafkaInput": {
    "topicKey": "maiazwe1glbiothdes",
    "startingOffsets": { "value": "earliest" },
    "jaasConfigurationKey": "keyVaultSecret",
    "groupId": "maiazwe1desiotconsumer",
    "avroSchemaUrl": "https://server/dataset"
  },
  "schemaDefinition": {"value": "json-schema"},
  "schemaJson": {
    "type": "struct",
    "fields": [
      {
        "name": "name",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "country",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "subcountry",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "geonameid",
        "type": "long",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "timeStamp",
        "type": "timestamp",
        "nullable": true,
        "metadata": {}
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-udf/dataset-full-snapshot-mask-asterisk-worldcities/dataset-full-snapshot-mask-asterisk-worldcities.json
{
  "name": "full-snapshot-mask-asterisk-worldcities",
  "description": "Dataset Full Snapshot World Cities",
  "sourceName": "source1",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database6",
  "table": "full_snapshot_mask_asterisk_worldcities",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "csv" },
    "filePattern": "<yyyy><mm><dd>_mask_asterisk_worldCities.csv",
    "csv": {
      "charset": "UTF-8",
      "header": { "value": "first_line"},
      "delimiter":  ","
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "country",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false,
        "transformation" : {
          "typ": {"value": "udf"},
          "udf": "mask-asterisk"
        }
      },
      {
        "name": "geonameid",
        "typ": {"value":  "long"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      },
      {
        "name": "timeStamp",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 5,
        "sensitive": false,
        "transformation" : {
          "typ": {"value": "date"},
          "pattern": "yyyy-MM-dd HH:mm:ss"
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-api/dataset-api-json-schema/dataset-api-json-schema.json
{
  "name": "dataset-api-json-schema",
  "description": "dataset api json schema",
  "sourceName": "source-api",
  "typ": { "value": "api" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "incremental" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database_api",
  "table": "json-schema",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "apiInput":{
    "endpoint": "People",
    "parameters": "",
    "pagination": {
      "typ": {"value" :"offset"},
      "top": "$top",
      "skip": "$skip",
      "topSize": 10
    },
    "dataIn": "value",
    "headers": {
      "content-type": "json"
    }
  },
  "schemaDefinition": {"value": "json-schema"},
  "schemaFile": "/source-api/dataset-api-full/dataset-api-fullsnapshot_schema.json",
  "schemaJson": {
    "type": "struct",
    "fields": [
      {
        "name": "UserName",
        "type": "string",
        "nullable": true
      },
      {
        "name": "Concurrency",
        "type": "long",
        "nullable": true
      },
      {
        "name": "FirstName",
        "type": "string",
        "nullable": true
      },
      {
        "name": "LastName",
        "type": "string",
        "nullable": true
      },
      {
        "name": "Gender",
        "type": "string",
        "nullable": true
      },
      {
        "name": "Emails",
        "type": {
          "type": "array",
          "elementType": "string",
          "containsNull": true
        },
        "nullable": true
      },
      {
        "name": "AddressInfo",
        "type": {
          "type": "array",
          "elementType": {
            "type": "struct",
            "fields": [
              {
                "name": "Address",
                "type": "string",
                "nullable": true
              },
              {
                "name": "City",
                "type": {
                  "type": "struct",
                  "fields": [
                    {
                      "name": "Country",
                      "type": "string",
                      "nullable": true
                    },
                    {
                      "name": "Region",
                      "type": "string",
                      "nullable": true
                    },
                    {
                      "name": "Name",
                      "type": "string",
                      "nullable": true
                    }
                  ]
                },
                "nullable": true
              }
            ]
          },
          "containsNull": true
        },
        "nullable": true
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-json-5/dataset-json-full-failfast-worldcities/dataset-full-failfast-worldcities-json.json
{
  "name": "full-snapshot-worldcities-json",
  "description": "Dataset Full Snapshot World Cities",
  "sourceName": "source-json-5",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database5",
  "table": "full_snapshot_worldcities_json",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "fileInput":{
    "format": { "value": "json" },
    "json": {
      "encoding": "UTF-8",
      "multiline": false,
      "allowUnquotedFieldNames": false,
      "allowNumericLeadingZeros": false
    },
    "filePattern": "<yyyy><mm><dd>_worldCities.json"
  },
  "schemaDefinition": {"value": "json-schema"},
  "schemaJson": {
    "type": "struct",
    "fields": [
      {
        "name": "name",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "country",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "subcountry",
        "type": "string",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "geonameid",
        "type": "long",
        "nullable": true,
        "metadata": {}
      },
      {
        "name": "timeStamp",
        "type": "timestamp",
        "nullable": true,
        "metadata": {}
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-api/dataset-api-json-columns/dataset-api-json-columns-2.json
{
  "name": "dataset-api-json-columns-2",
  "description": "dataset api json columns 2",
  "sourceName": "source-api",
  "typ": { "value": "api" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "full_snapshot" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database_api",
  "table": "jsoncolumns_2",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "apiInput":{
    "endpoint": "People",
    "parameters": "",
    "pagination": {
      "typ": {"value" :"offset"},
      "top": "$top",
      "skip": "$skip",
      "topSize": 10
    },
    "dataIn": "value",
    "headers": {
      "content-type": "json"
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "/source-api/dataset-api-full/dataset-api-fullsnapshot_schema.json",
  "schemaColumns": {
    "columns": [
      {
        "name": "UserName",
        "typ": {"value":  "string"},
        "isPrimaryKey": true,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Concurrency",
        "typ": {"value":  "long"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "FirstName",
        "typ": {"value":  "string"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "LastName",
        "typ": {"value":  "string"},
        "position": 2,
        "sensitive": false
      },
      {
        "name": "Gender",
        "typ": {"value":  "string"},
        "position": 3,
        "sensitive": false
      },
      {
        "name": "Emails",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "string"}
        },
        "position": 4,
        "isPrimaryKey": false,
        "isTimestamp": false,
        "sensitive": false
      },
      {
        "name": "AddressInfo",
        "typ": {"value":  "array"},
        "arrayInfo": {
          "elementType": {"value":  "struct"}
        },
        "position": 4,
        "isPrimaryKey": false,
        "isTimestamp": false,
        "sensitive": false
      },
      {
        "name": "City",
        "typ": {"value":  "struct"},
        "parentName": "AddressInfo",
        "sensitive": false
      },
      {
        "name": "Country",
        "typ": {"value":  "string"},
        "parentName": "City",
        "sensitive": false
      },
      {
        "name": "Region",
        "typ": {"value":  "string"},
        "parentName": "City",
        "sensitive": false
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "parentName": "City",
        "sensitive": false
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-excel-6/dataset-last-changes-worldcities/dataset-last-changes-worldcities.json
{
  "name": "last-changes-worldcities",
  "description": "Dataset last changes world cities",
  "sourceName": "source-excel-6",
  "typ": { "value": "file" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "last_changes" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "database6",
  "table": "last_changes_worldcities",
  "partitionBy": "yyyy/mm/dd",
  "permissiveThresholdType": {"value" :"percentage"},
  "permissiveThreshold": 20,
  "fileInput":{
    "format": { "value": "xls" },
    "filePattern": "<yyyy><mm><dd>_last_changes_worldCities.xlsx",
    "xls": {
      "header": { "value": "first_line"},
      "sheet": "Hoja1",
      "dataRange": "A2"
    }
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "country",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "subcountry",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "geonameid",
        "typ": {"value":  "long"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 4,
        "sensitive": false
      },
      {
        "name": "timeStamp",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 5,
        "sensitive": false,
        "transformation" : {
          "typ": {"value": "date"},
          "pattern": "yyyy-MM-dd HH:mm:ss"
        }
      }
    ]
  }
}

=== AlejandroAlcaraz32/MotorIndationIber/maven/src/test/resources/metadata/source-sqlserver/dataset-sqlserver/dataset-sqlserver-incremental-isTimestamp-alias-onlyNewData.json
{
  "name": "dataset-sqlserver-incremental-isTimestamp-alias-onlyNewData",
  "description": "dataset sqlserver incremental",
  "sourceName": "source-sqlserver",
  "typ": { "value": "table" },
  "version": 1,
  "enabled": true,
  "classification": { "value": "public" },
  "effectiveDate": "2020-07-03 10:10:00",
  "ingestionMode": { "value": "incremental" },
  "validationMode": { "value": "fail_fast" },
  "createDatabase": true,
  "database": "Production",
  "table": "ProductCategoryI_isTimestamp_alias_onlyNewData",
  "partitionBy": "",
  "permissiveThresholdType": {"value" :"absolute"},
  "permissiveThreshold": 10,
  "tableInput":{
    "table": "ProductCategoryIncremental",
    "schema": "Production",
    "query": "select * from Production.ProductCategoryIncremental where ModifiedDate > to_timestamp('isTimestampMaxSilverValue', 'yyyy-MM-dd HH:mm:ss.SSS')",
    "onlyNewData": true,
    "datePattern": "yyyy-MM-dd HH:mm:ss.SSS"
  },
  "schemaDefinition": {"value": "json-columns"},
  "schemaFile": "",
  "schemaColumns": {
    "columns": [
      {
        "name": "ProductCategoryID",
        "typ": {"value":  "integer"},
        "isPrimaryKey": true,
        "isTimestamp": false,
        "position": 1,
        "sensitive": false
      },
      {
        "name": "Name",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 2,
        "sensitive": false
      },
      {
        "name": "rowguid",
        "typ": {"value":  "string"},
        "isPrimaryKey": false,
        "isTimestamp": false,
        "position": 3,
        "sensitive": false
      },
      {
        "name": "ModifiedDate",
        "alias": "UpdateDate",
        "typ": {"value":  "datetime"},
        "isPrimaryKey": false,
        "isTimestamp": true,
        "position": 4,
        "sensitive": false
      }
    ]
  }
}
